### ISSUE TITLE
Add CI to all examples

### ISSUE THREAD

**Issue by potatodepaulo** [near/devx#42]

**Comment by amgando** [comment]
note, from Epic https://github.com/near/devx/issues/43, the following are possible related to this issue if we zoom out and think of it as "automation".  not sure if that's helpful

- [ ] all the examples run in gitpod and locally
- [ ] when the examples break, we know because of CI 
- [ ] dependencies in examples are autoupdated

**Comment by mikedotexe** [comment]
Can be seen here:
https://travis-ci.com/github/nearprotocol/awesome-near/builds
